# Generated by Django 5.2.4 on 2025-07-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(help_text="Укажите имя автора", max_length=30, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(help_text="Укажите фамилию автора", max_length=30, verbose_name="Фамилия"),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату рождения (гггг-мм-дд)",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Введите страну автора", max_length=50, null=True, verbose_name="Страна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название книги", max_length=255, verbose_name="Название книги"
                    ),
                ),
                (
                    "published_year",
                    models.PositiveIntegerField(help_text="Укажите год издания", verbose_name="Год издания"),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="Введите ISBN книги (13 цифр)", max_length=13, unique=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "total_copies",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Общее количество экземпляров книги",
                        verbose_name="Количество экземпляров",
                    ),
                ),
                (
                    "available_copies",
                    models.PositiveIntegerField(
                        default=1, help_text="Число доступных экземпляров", verbose_name="Доступно для выдачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Опционально: краткое описание книги", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Выберите автора книги",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["title"],
            },
        ),
    ]
