# Generated by Django 5.2.4 on 2025-07-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_genre_book_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
    ]
