# Generated by Django 5.2.4 on 2025-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_genre_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                error_messages={
                    "unique": "Книга с таким ISBN уже существует. Проверьте корректность или измените данные."
                },
                help_text="Введите ISBN книги (13 цифр)",
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birthday"),
                name="unique_author",
                violation_error_message="Автор с такими данными уже существует.",
            ),
        ),
    ]
