# Generated by Django 5.2.4 on 2025-07-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"verbose_name": "Выдача", "verbose_name_plural": "Выдачи"},
        ),
        migrations.AddField(
            model_name="loan",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="renewals_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
