# Generated by Django 5.2.4 on 2025-07-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_alter_loan_options_loan_due_date_loan_renewals_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"ordering": ["-loan_date"], "verbose_name": "Выдача", "verbose_name_plural": "Выдачи"},
        ),
    ]
